### ISSUE TITLE
Generic Host updates for 3.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/AspNetCore.Docs#11969]
For some of the following tasks it may be appropriate to create separate issues and PRs.

* [x] Host section of Fundamentals overview - review and update as needed. It already has 3.0 content in a moniker block. In the 2.x block add text advising that in 3.0 Generic Host is recommended over Web Host. #12794
* [x] Table of Contents - Reorder the Web Host and Generic Host nodes so Generic Host is first. #12816
* [x] Intro section of Web Host doc - in both 3.0 and 2.x moniker blocks include text advising that in 3.0 Generic Host is recommended over Web Host. #12873
* [x] Other docs that link to the Web Host doc - change links to point to the Generic Host doc or the Host section of the Fundamentals overview as appropriate. #12847
* [ ] App startup doc - injection restrictions: https://github.com/aspnet/Announcements/issues/353
* [ ] Generic Host doc - review and update as needed. It currently has 3.0 content only in the intro in a moniker block.

[EDIT by @guardrex: Just noting that this issue comment was updated to the latest guidance from engineering by @tdykstra.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
Also Startup injection restrictions: https://github.com/aspnet/Announcements/issues/353

**Comment by guardrex** [comment]
Call out on the special naming of the builder method when the Generic Host topic updates are made. This was addressed for the Web Host and in the Fundamentals Overview on https://github.com/aspnet/AspNetCore.Docs/pull/12384.

> \`CreateHostBuilder\` is special name that identifies the builder method to external components, such as \[Entity Framework](/ef/core/).
