### ISSUE TITLE
authentication/sociallogins "Enabling authentication using Facebook, Google and other external providers"

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore.Docs#1470]
[Edit by Rick-Anderson and GuardRex]
- [x] HaoK's complaint above
- [x] Specify the "Valid OAuth redirect URIs" for Facebook (and other providers). E.g. http://localhost:12345/signin-facebook. See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs#L22
- [ ] #1908  add copy the https URL also in the Launch URL from the Visual Studio IDE same page.
- [ ] update entire article
- [ ] #86 
- [x]  A walk-through for Google, MicrosoftAccount, LinkedIn and Twitter that highlights some if their eccentricities.
- [x]  A reference to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for additional providers
- [ ]  Requesting more data with Scopes (general oauth) and Fields (Facebook specific).
- [ ]  Using the OnCreatingTicket event to map additional data into claims
- [ ]  How to map provider claims into the Identity database
- [ ]  Specify the "Valid OAuth redirect URIs" for Facebook (and other providers). See Tratcher comment below
- [ ] ArgumentException: The 'ClientId' option must be provided #10680
- [ ] Instructions followed exactly still lead to errors (even if Google+ API is enabled) #10684

-- original which is now fixec
There appears to be a new step that needs to be done via App registration in facebook.

I got an error saying my AppDomain was not registered.

The fix is to add localhost to the AppDomain text box during the WebSite platform registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
- [ ] HaoK's complaint above
- [ ] update entire article

**Comment by Tratcher** [comment]
- Specify the "Valid OAuth redirect URIs" for Facebook (and other providers). E.g. http://localhost:12345/signin-facebook

**Comment by daveabrock** [comment]
I have also noticed this could use some TLC. Is anyone working on it? If not, I can start making some changes.

**Comment by Rick-Anderson** [comment]
@daveabrock  that would be great.

**Comment by daveabrock** [comment]
On it! I'll have a pull request soon in the next few days for cleanup and addressing @HaoK's comment (me seeing it myself brought me here) and then will address @Rick-Anderson's list a little later on.

**Comment by Rick-Anderson** [comment]
@daveabrock  can you review the check boxes at the top and let me know what's completed?

**Comment by Rick-Anderson** [comment]
@01binary can you review the check boxes at the top and let me know what's completed?

**Comment by 01binary** [comment]
@Rick-Anderson:

**A reference to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for additional providers**

See [Other Providers](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/other-logins.md) linked to from a bullet list on [Social Providers Index page](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/index.md#setup-login-providers-required-by-your-application). While this doesn't link to their GitHub page, it does link to NuGet packages (which I think is more convenient). The NuGet page then links to GitHub page with **Project Site** item on the left sidebar.

---

**Specify the "Valid OAuth redirect URIs" for Facebook (and other providers). See Tratcher comment below**

All social login pages in the following set:
[Facebook logins](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
[Google logins](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
[Microsoft logins](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
[Twitter logins] (https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)

Contain the following paragraph and two notes which address this issue:

Enter your current site URL with signin-**provider** appended into the Callback URL field. For example, https://localhost:44320/signin-**provider**.

[!NOTE] When deploying the site you'll need to register a new public url.
[!NOTE] You don't need to configure signin-twitter as a route in your app. The Twitter middleware automatically intercepts requests at this route and handles them to implement the OAuth flow.

Please note that the first post in this issue thread has not one but two checkboxes for duplicate issue (valid OAuth redirect URLs).

I am not seeing anything else that can be checked off at the moment.

**Comment by Rick-Anderson** [comment]
Moved to #16210
