### ISSUE TITLE
Master issue for  Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#16186]
Address the following issues. Reopen each issue if you don't fix all of them in one PR:

- [ ] How to check scopes in .NET Core 3.1 web api app? #16436
- [ ]  Try this tutorial and it doesn't work - needs update to access token Auth URL #13363
- [ ]  ASP.NET Core 2.2/3.0 preview Jwt Bearer to API example (non Postman) #13215
- [ ]  Please revise this entire document. #13094
- [ ]  Postman Callback Url has been changed #11750
- [ ]  Update documentation and mention that "grant_type=authorization_code" is possible as well (see description) #10336
- [ ]  Should be updated to use the new {tenant}.b2clogin.com endpoint #8998
- [ ]  Update to current: Cloud authentication in web APIs with Azure Active Directory B2C in ASP.NET Core #6401

17K PV in Nov 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by freemstr** [comment]
@CamSoper 
Which of the changes to documentation resolves #13215?
[This newly suggested link](https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/enable-webapp-signin/?view=aspnetcore-3.1)
[Points to non existent](https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-aspnetcore-webapp-openidconnect-v2/enable-webapp-signin/1-WebApp-OIDC/1-1-MyOrg)

It seems possible that there were changes in https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 while you were making your updates

Thank you.

**Comment by GedillurBjorn** [comment]
> @CamSoper

Same as @freemstr, removing the doc related to #13215 is not resolving it. I started learning code some times ago, and looking for an example of .net core web app to api with Azure AD B2C, but I was not able to find an example with Core 3.1.

**Comment by freemstr** [comment]
@GedillurBjorn 
For the lack of coherent centralized documentation from Microsoft despite multiple open tickets I suggest you look here: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#public-client-and-confidential-client-applications
https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics

This is also great for educational purposes (Thank you @TiagoBrenck )
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/192

@Rick-Anderson 
It is perplexing that while B2C is the cash generating paid service for MS its one area that does not have an end-to-end complete code example for the last 3 years. And all the open tickets were merged to this one just to be buried.

Out of the original tickets
 #16436, #13363,  #13215,  #13094, #11750, #10336, #8998, #6401

Which are ACTUALLY resolved by sweeping it under the rug aka "retiring a problem doc" #16650?

**Comment by CamSoper** [comment]
@freemstr @GedillurBjorn  I made the suggestion to @Rick-Anderson to retire it. It was badly broken, as the product changes on a fairly frequent basis and I don't have the bandwidth to update the doc at the pace at which the Azure AD B2C product changes. 

Since it's not really my area of expertise, I believe that the sample provided by the Microsoft identity platform team, the team that develops the Azure AD B2C product, is a far better experience for you. Especially since my tutorial was questionably written and conceived (again, my bad), and most importantly, it *doesn't work*. I've fixed it multiple times only for it to break again, and that's not helping users like you *at all*. 

I'm willing to be told that I'm wrong here, but for now I think that linking to the AAD B2C product's documentation and samples was the right call.

**Comment by TiagoBrenck** [comment]
@freemstr that PR might not get merged. We are now working on this one instead: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/pull/272

**Comment by GedillurBjorn** [comment]
@CamSoper I am sorry, I am not saying that your wrong, maybe miscommunication, having it removed and mark it resolved. I can understand that the pace of development for both B2C and .Net Core looks very fast, but I don't think it is too much to ask to have "complete" example for a basic thing such as web app --> api.

especially as in the docs for B2C there are examples for SPA/Desktop --> API, granted that it is probably the B2C team providing them.

**Comment by freemstr** [comment]
@CamSoper I absolutely agree that one person may not 
>  have the bandwidth to update the doc at the pace at which the Azure AD B2C product changes

And this is the very reason we NEED documentation to be complete and applicable, authentication is only a small portion of a modern commercial application, and .NET Core is changing just as fast; 
So if your sample kept breaking imagine what it is like for an architect to maintain a commercial product and hear from developers routinely:

>doesn't work. I've fixed it multiple times only for it to break again

However regarding,
>  linking to the AAD B2C product's documentation and samples was the right call

Please see https://github.com/aspnet/AspNetCore.Docs/issues/16186#issuecomment-578223941

It may very well be impossible for one person to maintain all examples' code
but I believe it is reasonable to expect docs.microsoft.com to catalog examples from both https://github.com/AzureAD and https://github.com/Azure-Samples as well as possibly other sources for newcomers to have access to up to date training.

Going forward, any suggestions on better venue for documentation requests other than here at https://github.com/aspnet/AspNetCore.Docs?
