### ISSUE TITLE
UE and other improvements

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#9239]
Moved from #1077
36K PV 78% CSAT

- [ ]  Use of URI and URL seems inconsistent in spots. Assess the use of these terms and possibly make updates to standardize. See #9640
- [ ] #9558 Route data on the HttpContext scenario #9558
- [ ] Remove version context from Routing #9552
- [ ]  Fix tables so they don't scroll
- [ ] We can now have conventional routing to middleware where you can define route templates with parameters and get a middleware/middleware-pipeline to be executed. Contact is `@kichalla or @rynowak`
- [x] Most apps shouldn’t need custom routes - That needs to be in intro.
- [ ]  Needs UE review (Create an instance of RouteBuilder, passing a reference to IApplicationBuilder. don't write in english what's in code)
- [ ] Explain snippets
- [ ] Explain when/why you would use routing
- [ ]  Explain the relationship between the routing middleware and MVC template routing.
- [ ] #1625
- [x] more exposition about the technical process of link generation.
- [x] What parts apply to Razor Pages?
- [ ] Map[Verb] extensions will need their own section.
- [ ] rewrite startup section/code

In RC2 Middleware later in the request pipeline can access route data using extensions methods on `HttpContext`. 
Also this behavior is updated to use an IRouteHandler.
An IRouter instance returns a delegate, or null (indicating the request was not handled).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per @guardrex 	

If this topic receives RP content, it probably should be linked near the top in *mvc/razor-pages/razor-pages-convention-features.md*. https://docs.microsoft.com/aspnet/core/mvc/razor-pages/razor-pages-convention-features

**Comment by IanKemp** [comment]
* Add information about the performance implication of many routes and/or many constraints. In particular, this could be hooked into the advice "Don't use constraints for input validation".
* "Warning" sections should have suggestions on what to do to avoid hitting that warning (e.g. for "Don't use constraints for input validation", link to a page or example showing the correct way to validate input).

**Comment by Structed** [comment]
Please also explain what "data tokens" are. These are casually mentioned and the reader is supposed to know what this is.

**Comment by Rick-Anderson** [comment]
Moved to Routing master issue #16501
